/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    Horse1SVG: typeof import('./src/components/svg/Horse1SVG.vue')['default']
    Horse2SVG: typeof import('./src/components/svg/Horse2SVG.vue')['default']
    Horse3SVG: typeof import('./src/components/svg/Horse3SVG.vue')['default']
    Horse4SVG: typeof import('./src/components/svg/Horse4SVG.vue')['default']
    HorseComponent: typeof import('./src/components/HorseComponent.vue')['default']
    HorseListComponent: typeof import('./src/components/HorseListComponent.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    RaceTrackComponent: typeof import('./src/components/RaceTrackComponent.vue')['default']
    RaceTrackRowComponent: typeof import('./src/components/RaceTrackRowComponent.vue')['default']
    RankingTableComponent: typeof import('./src/components/RankingTableComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
  }
}
